routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\UserController;
use App\Http\Controllers\BranchController;
use App\Http\Controllers\LoanTypeController;
use App\Http\Controllers\LoanTypePayModeController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\OccupationController;
use App\Http\Controllers\MarketingChannelController;
use App\Http\Controllers\TransactionTypeController;
use App\Http\Controllers\BatchController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\PMESController;
use App\Http\Controllers\BankMasterController;
use App\Http\Controllers\MemberMasterController;
use App\Http\Controllers\OnlinePymntTrxnMasterController;
use App\Http\Controllers\OnlinePymntTrxnDetailController;
use App\Http\Controllers\AcctMasterController;
use App\Http\Controllers\PreLoanApplicationController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\MIUFController;
use App\Http\Controllers\VerificationController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\HomeController;
use App\Http\Livewire\Batchv1;
use Illuminate\Http\Request;
use App\Models\PreLoanApplication;
use App\Models\OnlinePymntTrxnMaster;
use App\Models\UserMember;
use App\Models\MIUF;
use App\Models\Feedback;
use App\Models\SiteFeedback;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;
use App\Mail\SendMail;
use App\Mail\LoanMail;
use App\Mail\OnlinePaymentMail;
use App\Exports\PMESExport;
use App\Exports\LoanExport;
use App\Exports\OnlinePaymentExport;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);

Route::get('/filedoc/{input}', [OnlinePymntTrxnMasterController::class, 'pdfview'])->name('filedoc');

Route::get('/auth-check', function(){
    if(!Auth::check()){
    return "logged out";
    }else{
    return "logged in";
    }
});

Route::get('/allnull/{input}', function(Request $request){
	$input = $request->input;
	if($input == 'miuf'){
		$exportNull = MIUF::all();
	foreach($exportNull as $data){
            $miufupdate = MIUF::find($data->id);
            $miufupdate->status = null;
            $miufupdate->encode_by = null;
            $miufupdate->encode_date = null;  
            $miufupdate->save();
        }
	}elseif($input == 'feedback'){
		$exportNull = Feedback::all();
	foreach($exportNull as $data){
            $miufupdate = Feedback::find($data->id);
            $miufupdate->status = null;
            $miufupdate->save();
        }
	}else{
		$exportNull = SiteFeedback::all();
	foreach($exportNull as $data){
            $miufupdate = SiteFeedback::find($data->id);
            $miufupdate->status = null;
            $miufupdate->save();
        }
	}

    return "success";

});


Route::get('/force-logout', function(){
    Auth::logout();
    return redirect()->to('/')->with('warning', 'Force logout activated.');
});

Route::get('/clear-cache', function(){
Artisan::call('optimize:clear');
return "Cache is Cleared";
});
Route::get('/clear-route', function(){
Artisan::call('route:clear');
return "Route is Cleared";
});
Route::get('/route-list', function(){
Artisan::call('route:list');
dd(Artisan::output());
});


Auth::routes(

);

Route::get('/demomail/{input}/{input1}', function ($input, $input1) {
	// dd($input);
	if($input == 'pmes'){
		if($input1 == 0){
            $link = 'https://meet.google.com/testing';
            $description = 'Online Pre-Membership Education Webinar';
            $meeting_cd = 'testing code';
        }elseif($input1 == 1){
            $link = 'https://us05web.zoom.us/j/86189281691?pwd=aWJSMVRDM2xRQURIcTNVcXRrOTMvQT09';
            $description = 'Online Pre-Membership Education Webinar';
            $meeting_cd = null;
        }else{
            $link = null;
                $meeting_cd = null;
            $description = 'Online Pre-Membership Education Seminar';
        }

		$startdate =  \Carbon\Carbon::parse('6 March 2019 15:00')->format('Ymd\THis');
		$enddate =  \Carbon\Carbon::parse('6 March 2019 17:00')->format('Ymd\THis');            
		$details = 
	                [
	                	'vid_tool' => $input1,
	                'link'   => $link,
            		'meeting_cd' => $meeting_cd,
	                'sched_date' => '2021-10-15 05:23:04',
	                'resched_remarks' => 'testing',
	                'text' => 'Creating calender feeds',
	                'description' => $description,
	                'startdate' => $startdate,
	                'enddate' => $enddate,
	                ];
	    return new App\Mail\SendMail($details);
	}elseif($input == 'verification'){
	    $details = 
	                [
	                'id' => '204',
	                'token' => 'o2PiKJxCaqoSJkVma2U4',
	                ];
	    return new App\Mail\VerificationMail($details);	
	}elseif($input == 'loan'){
		$decline_type = $input1;
		if($decline_type == 'temp'){
			$remarks = 'your attachment is not up to snuff';
		}elseif($decline_type == 'final'){
			$remarks = 'sorry but your application is declined';
		}else{
			$remarks = 'approved'; 
		}
		$details = [
            'decline_type' => $decline_type,
            // 'decline_type' = $decline,
            'remarks' => $remarks,
        ];
        // dd($details);
	    return new App\Mail\LoanMail($details);
	}elseif($input == 'payment'){
		
		$details = [
            'receipt' 	=> 'ortesting',
            'ORPDF'		=> '51820220228-optmor.pdf'
        ];
        // dd($details);
	    return new App\Mail\OnlinePaymentMail($details);
	}

});


Route::get('/demoexport/{input}/{input1}/{input2}', function ($input, $input1,$input2) {
	// dd($input1.' '.$input2);
        $start = $input1.' 00:00:00';
        $end = $input2.' 23:59:59';
        $date = date('M-d-Y', strtotime($start)).'-'.date('M-d-Y', strtotime($end));
	 return \Excel::download(new OnlinePaymentExport($start, $end), 'Online Payment('.$date.').'.'xlsx');
});


 
Route::get('/verifyEmail/{id}/{token}', [App\Http\Controllers\ClientController::class, 'verifyEmail'])->name('verifyEmail');

Route::get('/enduser-verify', [App\Http\Controllers\MemberMasterController::class, 'member_verify'])->name('enduser-verify');
Route::get('/enduser/register', [App\Http\Controllers\MemberMasterController::class, 'member_register'])->name('enduser.register');
Route::post('/enduser/storeusermember', [App\Http\Controllers\MemberMasterController::class, 'storeusermember'])->name('enduser.storeusermember');

Route::get('/validateEmail/', [MemberMasterController::class, 'validateEmail'])->name('validateEmail');

Route::get('/payment_modeAPI/{id}', [PreLoanApplicationController::class, 'payment_modeAPI'])->name('payment_modeAPI');
Route::get('/payment_termAPI/{id}', [PreLoanApplicationController::class, 'payment_termAPI'])->name('payment_termAPI');
Route::get('/payment_termMonths/{id}', [PreLoanApplicationController::class, 'payment_termMonths'])->name('payment_termMonths');
Route::get('/loanstatusAPI/{id}', [PreLoanApplicationController::class, 'loanstatusAPI'])->name('loanstatusAPI');

Route::get('/feedbackAPI/{input}', [FeedbackController::class, 'feedbackAPI'])->name('feedbackAPI');
Route::get('/lastFeedback', [FeedbackController::class, 'lastFeedback'])->name('lastFeedback');
Route::get('/lastFeedbackNonRegNonMem', [FeedbackController::class, 'lastFeedbackNonRegNonMem'])->name('lastFeedbackNonRegNonMem');


Route::get('/enduser/feedback', [App\Http\Controllers\FeedbackController::class, 'create'])->name('enduser.feedback');
Route::post('/feedback.store', [App\Http\Controllers\FeedbackController::class, 'store'])->name('feedback-store');
// Route::get('/enduser/login', [App\Http\Controllers\MemberMasterController::class, 'login'])->name('enduser.login');





	

Route::group(['middleware' => 'is_enduser'], function () {
	Route::get('/email/verify', [App\Http\Controllers\VerificationController::class, 'show'])->name('verification.notice');
    Route::get('/email/verify/{id}/{hash}', [App\Http\Controllers\VerificationController::class, 'verify'])->name('verification.verify')->middleware(['signed']);
    Route::post('/email/resend', [App\Http\Controllers\VerificationController::class, 'resend'])->name('verification.resend');
    
		Route::get('/enduser/edit', [App\Http\Controllers\MIUFController::class, 'edit'])->name('enduser.edit');
		Route::post('/enduser/update', [App\Http\Controllers\MIUFController::class, 'update'])->name('enduser.update');

	Route::group(['middleware' => 'is_verified'], function () {

	Route::get('/validateCoMaker/', [MemberMasterController::class, 'validateMemberNo'])->name('validateCoMaker');

		Route::get('/enduser/sitefeedback/{input}', [App\Http\Controllers\SiteFeedbackController::class, 'create'])->name('enduser.sitefeedback');
		Route::post('/sitefeedback.store', [App\Http\Controllers\SiteFeedbackController::class, 'store'])->name('sitefeedback-store');

		Route::get('/sitefeedbackAPI/{input}', [App\Http\Controllers\SiteFeedbackController::class, 'sitefeedbackAPI'])->name('sitefeedbackAPI');
		Route::get('/lastsiteFeedback', [App\Http\Controllers\SiteFeedbackController::class, 'lastsiteFeedback'])->name('lastsiteFeedback');
		Route::get('/lastsiteFeedbackNonRegNonMem', [App\Http\Controllers\SiteFeedbackController::class, 'lastsiteFeedbackNonRegNonMem'])->name('lastsiteFeedbackNonRegNonMem');


		Route::get('enduser/home', [HomeController::class, 'memberHome'])->name('enduser.home');

		Route::get('/preloan/create', [App\Http\Controllers\PreLoanApplicationController::class, 'create'])->name('preloan.create');

app/Http/Livewire/Batchv1.php
<?php

namespace App\Http\Livewire;

use App\Models\Batch;
use App\Models\PMES;
use App\Models\Client;
use Livewire\Component;
use Livewire\WithPagination;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Illuminate\Foundation\Auth\RegistersUsers;
use Illuminate\Support\Facades\Hash;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Mail;
use App\Mail\SendMail;

class Batchv1 extends Component
{
    use WithPagination;
    public $searchTerm;
    public $batch, $batch_cd,$sched_date,  $meeting_cd, $meeting_pw, $online_vid_tool, 
     $batch_id, $resched_remarks;
    public $updateMode = false;
    public $participant = null;
    public $client_id = null;
    public $client_name = null;

    public function render()
    {
        $mindate = Carbon::now()->addDay()->format('Y-m-d H:i');
                // $sched_date = Carbon::parse($this->sched_date)->format('Y-m-d H:i');

        $now = Carbon::now()->format('m/d/Y');
        $now1 = Carbon::now();
        $participant = null;
        // dd($mindate);
        $searchTerm = '%'.$this->searchTerm.'%';
        return view('livewire.batch.index',
        ['batch1' => Batch::where('batch_cd','like', $searchTerm)
        ->whereNull('soft_deleted_at')
        ->whereDate('sched_date', '>=' , $now1)
        ->get(),'now' =>$now, 'mindate' => $mindate, 'participant', $participant]);
    }
    private function resetInputFields(){
        $this->batch_cd = null;
        $this->meeting_cd = null;
        $this->meeting_pw = null;
        $this->online_vid_tool = null;
        $this->resched_remarks = null;
    }

    public function store()
    {
        $sched_date = Carbon::parse($this->sched_date)->format('Y-m-d H:i');
        // dd($sched_date);
        $validatedDate = $this->validate
        ([
            'batch_cd' => 'required',
            'sched_date' => 'required',
            'online_vid_tool' => 'required',
            'meeting_cd' => 'required',
        ]);
        $batch = [
             'batch_cd' => $this->batch_cd,
                ];
        $batch_revive = ['soft_deleted_at' => null,
             'sched_date' => $sched_date,
             'online_vid_tool' => $this->online_vid_tool,
            'meeting_cd' => $this->meeting_cd,
             'batch_stat' => 0,
            'meeting_pw' =>$this->meeting_pw,
            'crea_by' => auth()->user()->uname,];
       // Batch::updateOrcreate($batch, $batch_revive);

        // $this->updateMode = false;
        session()->flash('success', 'Batch Created Successfully.');
        $this->resetInputFields();

        $this->emit('batchStore'); // Close model to using to jquery

    }
    public function edit($id)
    {

        $batch = Batch::where('id',$id)->first();
        // $sched_date = Carbon::parse($batch->sched_date)->format('Y-m-d'.'\T'.'H:i:s.v');
        $sched_date = Carbon::parse($this->sched_date)->format('Y-m-d H:i');

        $this->batch_id = $id;
        $this->batch_cd = $batch->batch_cd;
        $this->sched_date = $sched_date;
        $this->online_vid_tool = $batch->online_vid_tool;
        $this->meeting_cd = $batch->meeting_cd;
        $this->meeting_pw = $batch->meeting_pw;
        $this->resched_remarks = $batch->resched_remarks;
        $this->updateMode = true;
        // dd($this);
    }
    public function participant($id)
    {
        $this->updateMode = true;
        $this->participant = 1;
       $this->client_name = PMES::with('client')->where('batch_id',$id)->get();
       
    }
     public function cancel()
    {
        $this->updateMode = false;
        $this->resetInputFields();

    }
    public function getBatches($batch_id)
    {
        $batches = Batch::where("id",$batch_id)->get(['sched_date','online_vid_tool','meeting_cd','meeting_pw']);
        return response()->json($batches);
    }
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'batch_cd' => ['required','unique:batch,batch_cd,'],
            'sched_date' => 'required',
            'online_vid_tool' => 'required',
            'meeting_cd' => 'required',
        ]);
    }
    public function update(Batch $batch)
    {   
        $array = array('batch_cd' => $this->batch_cd,'sched_date' => $this->sched_date,'online_vid_tool' => $this->online_vid_tool,'meeting_cd' => $this->meeting_cd, );
        // dd($this);
        $this->validator($array);
        
        // $sched_date = Carbon::parse($this->sched_date)->format('Y-m-d'.'\T'.'H:i:s.v');
        $sched_date = Carbon::parse($this->sched_date)->format('Y-m-d H:i');

        if ($this->batch_id) 
        {
            $batch = Batch::find($this->batch_id);
            $batch->update
        ([
            'batch_cd' => $this->batch_cd,
            'sched_date' => $sched_date,
            'online_vid_tool' => $this->online_vid_tool,
            'meeting_cd' => $this->meeting_cd,
            'meeting_pw' => $this->meeting_pw,
            'resched_remarks' => $this->resched_remarks,
        ]);
            // $this->updateMode = false;
            session()->flash('success', 'Batch!!! Updated Successfully.');
            $this->resetInputFields();
        }
        $pmes = PMES::with('client')->where('batch_id', $this->batch_id)->get();
        if($pmes->count())
        {
            foreach($pmes as $data)
            {
                // dd($data->client->gmail_address);
                $meeting_cd = Batch::where('id', $this->batch_id)->first()->meeting_cd;
                $sched_date = Batch::where('id', $this->batch_id)->first()->sched_date;
                $resched_remarks = Batch::where('id', $this->batch_id)->first()->resched_remarks;
                $email = $data->client->gmail_address;
                $details = 
                [
                'meeting_cd' => $meeting_cd,
                'sched_date' => $sched_date,
                'resched_remarks' => $resched_remarks
                ];

                $editclient = Client::find($data->client->id);
                $editclient->sched_date = $sched_date;
                $editclient->save();
                // dd($meeting_cd);
                Mail::to($email)->queue(new SendMail($details));
            }
        }
    }

    
}

app/Http/Livewire/SearchBatchHistory.php
<?php

namespace App\Http\Livewire;

use App\Models\Batch;
use Livewire\Component;
use Livewire\WithPagination;
use Carbon\Carbon;

class SearchBatchHistory extends Component
{
    use WithPagination;
    public $searchTerm;

    public function render()
    {

        $now = Carbon::now()->format('m/d/Y');
        $now1 = Carbon::now();
        $searchTerm = '%'.$this->searchTerm.'%';
        return view('livewire.batch.index-history',
        ['batch' => Batch::whereDate('sched_date','like', $searchTerm)->orWhere('batch_cd','like', $searchTerm)
        ->orderBy('sched_date', 'DESC')
        ->paginate(10),'now' =>$now]);
    }
}

app/Http/Livewire/SearchClient.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Livewire\WithPagination;
use Carbon\Carbon;
use App\Models\Client;


class SearchClient extends Component
{
    use WithPagination;
    public $searchTerm;

    public function render()
    {

        
        $searchTerm = '%'.$this->searchTerm.'%';
        return view('livewire.client.search-client',
        ['client' => Client::where('fullname','like', $searchTerm)
        ->orWhere('gmail_address','like', $searchTerm)
        ->orWhere('contact_no','like', $searchTerm)
        ->paginate(10)]);
    }
}

resources/views/livewire/batch/create.blade.php
<button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal">
    <li class="fas fa-plus-circle fa-lg"  aria-hidden="true"></li>
</button>



<!-- Modal -->
<div wire:ignore.self class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create Batch</h5>
                <button type="button" onClick="window.location.reload();" class="close" wire:click="cancel" data-dismiss="modal" aria-label="Close">
                     <span aria-hidden="true close-btn">×</span>
                </button>
            </div>
           <div class="modal-body">
                <form>
                    <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Batch Code') }}</label>

                            <div class="col-md-6">
                                <input id="batch_cd" type="text" wire:model="batch_cd" class="form-control @error('batch_cd') is-invalid @enderror" name="batch_cd" value="{{ old('batch_cd') }}" required autocomplete="batch_cd" autofocus />

                                @error('batch_cd')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Schedule Date and Time</label>
                             <div class="col-md-6">
                                <input type="datetime" wire:model="sched_date" class="form-control"  name="sched_date" min="{{$mindate}}" id="dateInput1">
                                <span class="text-danger">
                                    <strong>{{$errors->first('sched_date') ?? null}}
                                    </strong>
                                </span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="employee_role" class="col-md-4 col-form-label text-md-right">{{ __('Preferred Application') }}</label>

                            <div class="col-md-6">
                                <select name="online_vid_tool" wire:model="online_vid_tool" class="form-control">
                                                <option value="">Select...</option>
                                                <option value = 0>Google Meet</option>
                                </select>
                                @error('online_vid_tool')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="meeting_cd" class="col-md-4 col-form-label text-md-right">{{ __('Meeting Code') }}</label>

                            <div class="col-md-6">
                                <input id="meeting_cd" wire:model="meeting_cd" type="text" class="form-control @error('meeting_cd') is-invalid @enderror" name="meeting_cd" value="{{ old('meeting_cd') }}" required autocomplete="meeting_cd" autofocus />

                                @error('meeting_cd')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        

                        <div class="form-group row">
                            <label for="meeting_pw" class="col-md-4 col-form-label text-md-right">{{ __('Meeting Password') }}</label>

                            <div class="col-md-6">
                                <input id="meeting_pw" wire:model="meeting_pw" type="meeting_pw" class="form-control @error('meeting_pw') is-invalid @enderror" name="meeting_pw" required autocomplete="new-meeting_pw">

                                @error('meeting_pw')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" tabindex="-1" class="btn btn-secondary close-btn" data-dismiss="modal">Close</button>
                <button type="button" wire:click.prevent="store()" class="btn btn-primary close-modal">Save</button>
            </div>
        </div>
    </div>
</div>

resources/views/livewire/batch/home-history.blade.php
@extends('layouts.app', [
    'class' => 'sidebar-mini ',
    'namePage' => 'Batch Index',
    'activePage' => 'batch-management',
    'activeNav' => '',
])

@section('indexdeleteall')
  <script src="{{ asset('assets') }}/js/indexdeleteall.js"></script>
@endsection
@section('content')
<div>
    @livewire('search-batch-history')
</div>
@endsection

resources/views/livewire/batch/home.blade.php
@extends('layouts.app', [
    'class' => 'sidebar-mini ',
    'namePage' => 'Batch Index',
    'activePage' => 'batch-management',
    'activeNav' => '',
])

@section('indexdeleteall')
  <script src="{{ asset('assets') }}/js/indexdeleteall.js"></script>
@endsection
@section('content')
<div>
    @livewire('batchv1')
</div>
@endsection
@section('batchscript')

<script src="{{ asset('assets') }}/js/batchdatepicker.js"></script>
<script src="{{ asset('assets') }}/js/editbatchdatepicker.js"></script>
<script type="text/javascript">
     window.addEventListener('DOMContentLoaded', event => {
    // Simple-DataTables
    // https://github.com/fiduswriter/Simple-DataTables/wiki
    
    const datatablesSimple = document.getElementById('datatablesSimple');
    if (datatablesSimple) {
        new simpleDatatables.DataTable(datatablesSimple, {
    searchable: false,
    fixedHeight: true
        });
    }
  });
        window.livewire.on('batchStore', () => {
            $('#exampleModal').modal('hide');
            $('.modal-backdrop').remove();
            setTimeout(function(){
   // alert('hei');
       $("div.alert").remove();
    }, 5000);
        });
</script>
@endsection

resources/views/livewire/batch/index-history.blade.php
  <div class="content">
<div class="panel-header panel-header-sm">
</div>
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            @include('flash-message')
                <div class="float-left">
                    <h4 class="card-title">Batch History</h4>
                </div>
                <div class="float-right">
                    <a class="btn btn-primary" href="{{ url('/batch') }}">
                        Batch Index
                    </a>
                </div>
          </div>
            <div class="card-body">
            <input type="text"  class="form-control" placeholder="Search Batch Code or Schedule Date" wire:model="searchTerm" />
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                    <th >Batch Code</th>
                    <th>Schedule Date</th>
                    <th>Schedule Time</th>
                    <th>Pref. Application</th>
                    <th class="meeting-col">Meeting Link</th>
                    <th class="shorten_text">Reschedule Remarks</th>
                    <th>Meeting Password</th>
                    <th>Participant Number</th>
                    <th>Batch Status</th>
                    <th>Date Created</th>
                    <th>Created By</th>
                </thead>
                <tbody>
                    @if($batch->count())
                    @foreach ($batch as $data)
                    <tr>
                    <td>{{ $data->batch_cd }}</td>
                    
                    <td>{{ \Carbon\Carbon::parse($data->sched_date)->format('m-d-Y')}}</td>
                    
                    <td>{{ \Carbon\Carbon::parse($data->sched_date)->format('h:i a')}}</td>
                    
                    @if($data->online_vid_tool == 0)
                    <td>Google Meet</td>
                    @endif
                    
                    <td class="meeting-col"><a href="https://meet.google.com/{{$data->meeting_cd}}">https://meet.google.com/{{$data->meeting_cd}}</a></td>

                    <td>{{$data->resched_remarks}}</td>
                    
                    @if(is_null($data->meeting_pw))
                    <td></td>
                    @else
                    <td>{{$data->meeting_pw}}</td>
                    @endif
                    <td>{{$data->participant}}</td>

                    @if(\Carbon\Carbon::parse($data->sched_date)->format('m/d/Y') == $now)
                    <td>Today</td>
                    @elseif(\Carbon\Carbon::parse($data->sched_date)->format('m/d/Y') <= $now)
                    <td>Expired</td>
                    @elseif($data->resched_remarks !== '.')
                    <td>Rescheduled</td>
                    @elseif(!is_null($data->soft_deleted_at))
                    <td>Soft Deleted</td>
                    @elseif($data->participant < 5)
                    <td>Insufficient Participant</td>
                    @else
                    <td>Pending</td>
                    @endif
                    
                    <td>{{ date_format($data->created_at, 'm-d-Y') }}</td>
                    
                    <td>{{ $data->crea_by }}</td>
                    </tr>
                    @endforeach
                    @endif
                </tbody>
              </table>
            </div>
              {{ $batch->links() }}
          </div>
        </div>
      </div>
      
    </div>
  </div>

resources/views/livewire/batch/participant.blade.php
<!-- Modal -->
<div wire:ignore.self class="modal fade" id="participantModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
       <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Participant List</h5>
                <button type="button" class="close" wire:click="cancel" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body table-responsive">
                    <table class="table">
                        <thead class=" text-primary">
                            <th>
                                Fullname
                            </th>
                            <th>
                                Contact Number
                            </th>
                            <th>
                                Email
                            </th>
                            <th>
                                Attendance
                            </th>
                        </thead>
                        <tbody>
                    @if(isset($this->participant))
                    @foreach($this->client_name as $items)
                    <tr>
                        <td>
                    {{$items->client->fullname}}
                        </td>
                        <td>
                    {{$items->client->contact_no}}
                        </td>
                        <td>
                    {{$items->client->gmail_address}}
                        </td>
                    @if($items->client->attendance == 1)
                        <td>
                        Present
                        </td>
                    @elseif($items->client->attendance == 2)
                        <td>
                        Absent
                        </td>
                    @else
                        <td>
                        Pending
                        </td>
                    @endif
                    </tr>
                    @endforeach
                    @endif
                        </tbody>
                    </table>
            </div>
            <div class="modal-footer">
                <button type="button" wire:click.prevent="cancel()" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
       </div>
    </div>
</div>